### ISSUE TITLE
[Bug]Unexpected node name error

### ISSUE THREAD

**Issue by kogekiplay** [getsurfboard/surfboard#191]
t4.v: java.lang.IllegalArgumentException: decode proxy failed: 📝 ISP：Hong Kong - Sharon Networks, LLC=ss,1.1.1.1,28051,encrypt-method=aes-128-gcm,password=password,tfo=true,udp-relay=true, java.lang.IllegalArgumentException: proxy type 📝 isp：hong kong - sharon networks is not supported
 at g6.v.b(Proxy.kt:2744)
 at g6.k.j(ProfileDecoder.kt:45)
 at g6.k.h(ProfileDecoder.kt:214)
 at h6.o.t(FetchProfileRequest.kt:158)
 at t4.j.a(NetworkDispatcher.java:90)
 at t4.j.run(NetworkDispatcher.java:6)

**Comment by getsurfboard** [comment]
Please do not include comma in your proxy name, which will may ini format decode not work properly.
